--在USRES表中插入数据
INSERT INTO USERS(USER_NAME,USER_ID,USER_PWD)VALUES('Mxy','0001','0001');
INSERT INTO USERS(USER_NAME,USER_ID,USER_PWD)VALUES('Yjt','0002','0002');
INSERT INTO USERS(USER_NAME,USER_ID,USER_PWD)VALUES('Ldg','0003','0003');
INSERT INTO USERS(USER_NAME,USER_ID,USER_PWD)VALUES('MT','0004','0004');

--在WORDS_STOCK表中插入数据
 INSERT INTO WORDS_STOCK(WORD_NUM,CLASS_NUM,WORDS,SOUNDMARK,TRANSLATIONS,EXAMPLE)VALUES('ws1','c1','wing','/wi?/','n.翼，翅膀，翅','a');
 INSERT INTO WORDS_STOCK(WORD_NUM,CLASS_NUM,WORDS,SOUNDMARK,TRANSLATIONS,EXAMPLE)VALUES('ws2','c2','unique','/ju:’ni:k/','a.唯一的，独一无二的','a');
 INSERT INTO WORDS_STOCK(WORD_NUM,CLASS_NUM,WORDS,SOUNDMARK,TRANSLATIONS,EXAMPLE)VALUES('ws3','c3','urban','/?:b?n/','都市的,住在都市的','a');
 INSERT INTO WORDS_STOCK(WORD_NUM,CLASS_NUM,WORDS,SOUNDMARK,TRANSLATIONS,EXAMPLE)VALUES('ws4','c4','troop','/tru:p/','n.军队；一群，大量','a');

--在CLASSES表中插入数据
INSERT INTO CLASSES(CLASS_NUM,CLASS_NAME)VALUES('C1','初中');
INSERT INTO CLASSES(CLASS_NUM,CLASS_NAME)VALUES('C2','高中');
INSERT INTO CLASSES(CLASS_NUM,CLASS_NAME)VALUES('C3','四级');
INSERT INTO CLASSES(CLASS_NUM,CLASS_NAME)VALUES('C4','六级');

--在CHOOSE表中插入数据
INSERT INTO CHOOSE (USER_ID, WORD_NUM) VALUES ('0001', 'ws1');
INSERT INTO CHOOSE (USER_ID, WORD_NUM) VALUES ('0002', 'ws2');
INSERT INTO CHOOSE (USER_ID, WORD_NUM) VALUES ('0003', 'ws1');
INSERT INTO CHOOSE (USER_ID, WORD_NUM) VALUES ('0001', 'ws3');

--在ADMIN表中插入数据
 INSERT INTO ADMIN(ADMIN_ID,ADMIN_NAME,ADMIN_PWD)VALUES('001','张三','001');
 INSERT INTO ADMIN(ADMIN_ID,ADMIN_NAME,ADMIN_PWD)VALUES('002','李四','002');
 INSERT INTO ADMIN(ADMIN_ID,ADMIN_NAME,ADMIN_PWD)VALUES('003','王五','003');

